# -*- coding: utf-8 -*-
"""Strings

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1l47sPcPP7c8rM5pX-gMvlVjmvoVEUZ0c
"""

#Strings

#loop with string 

fruit = 'banana'

index = 0

while index < len(fruit):
    letter = fruit[index]
    print(index,letter)
    index += 1

#for loop for  iteration varible
for letter in fruit:
    print(letter)

word = 'banana' 
count = 0
for letter in word :
  if letter == 'a' :
    count = count + 1
    print(count)

#String Slicing

s = 'Hello World'
print(s[0:4]) #look its printing only three word
print(s[6:7]) 
print(s[6:20]) #Give no traceback end at 11

print(s[:2]) #print letters before index 2
print(s[8:]) #print letter after index 8
print(s[:]) #print all

#String Manipulation

fruit = 'banana'

'm' in fruit  #check if m is in banana 

'nan' in fruit

if 'a' in fruit :
  print('Found it !')

#string comparison
word = 'banana'
if word == 'banana' :
  print('All right,bananas') #this if compare string

if word < 'banana' :
  print('Your word,'+ word +',comes before banana') #this also compare if less than banana

if word > 'banana' :
  print('Your word,'+ word +',comes after banana')

#String Library
greet = 'HeLlo Bob'
zap = greet.lower() #print lower case
print(zap) 
#or
print('HELLO'.lower())

stuff = 'Hello WORLD'
type(stuff)
dir(stuff) #shows what can you do with this datatype

#i.e
name = "siddhesh"
print(name.capitalize()) #first letter capital
print(name.upper())

#searching string

string = 'hello world'
pos = string.find('lo')
print(pos)
print(string.find('k')) #return -1 did not find

#Search and Replace
name = 'Hello Sid'
var = name.replace('Sid','Jay')
print(var) 

var1 = name.replace('o','X')
print(var1)

#Stripping Whitespace

name = "   siddhesh  sid"
name.lstrip() #left strip
name.rstrip() #right
name.strip()

#Prefixes
line = 'Please have a nice day'
line.startswith('Please')

#Parsing and extracting
data = 'From stephen.marquard@uctt.ac.za Sat Jan 5 09:14:16 2008'
atposition = data.find('@')
print(atposition) #tell position

atposition2 = data.find(' ',atposition)
print(atposition2)

host = data[atposition+1 : atposition2] # +1 for remove @
print(host)

#String Slicing

string ="sidhesh gaykar"

print(string)
print(string[0:6])
print(string[0:20:3]) #here 3 is used to select every 3rd string in 20
print(string[-1]) #negative indexing
print(string[-5:-1])

#string functions
string.count("a")
string.find("e")

len(string) #calculate total length of string
print(string.rfind("r")) #last occurance of string

#Boolean
x = True
print(x)
y = False
print(y)

#printing
x = 5
print(f"Value is {x}")

str = "{hello} is teaching programing"
str.format(hello ="siddhesh")